# I use global env to facilitate debug, since they exist as soon as you enter the shell
dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $HOME/.local/lib/R/]
env:
  global: 
    - input_git=$TRAVIS_BUILD_DIR
    - repo_git="-b zhuoer-nutshell https://$GITHUB_PAT@github.com/dongzhuoer/bookdown.dongzhuoer.com.git"
    - rmd_dir=.
    - root_command=""   
    - user_command=""
    - install_pkg="remotes::update_packages(c('magrittr', 'tidyverse', 'cowplot', 'testthat', 'plyr', 'gridExtra', 'nutshell', 'learningr', 'lattice'))"
    - render_args=""
    - zhuoerdown=false
script: wget https://raw.githubusercontent.com/dongzhuoer/zhuoerdown/master/inst/travis-script.sh && bash travis-script.sh

notifications:
  email: false
