# Linux tools

- `which`
- `whatis` 
- `apropos`
- `type`



## Git

Git 千万不要把 branch 想象成一整段树枝 ^[在我入门后，这种思维使我很难理解一些高级操作，本以为要看书学会全部 implementation 细节才能弄懂，没想到（2021-02-21）在处理实际问题时先把这个学会了，其它的不学也没关系。]，branch 只是 commit 树的一个指针而已，迭代追溯父节点即可得树枝。

如 A->B->C->D，如果 master 指向 D，那么一直向前到起点就是 DCBA；把 master `reset` 到 C 后，就变成 CBA。

- 当前修改暂不 commit，但又担心丢失，就用 branch 来保存

记住 master hash，如 074c; 建立新 branch（如 temp），commit 修改

```bash
git checkout master    # working tree 与上次 commit 一摸一样
git reset --hard temp  # 找回当前修改，副作用使 master 与 temp 一样
git reset 074c         # 把 master 重新指向上次 commit
```

- commands

```bash
git clean -fd		 # remove all untracked File and Directory
git update-index --assume-unchanged path/to/file  # untrack
git help co   # print alias
```

- orphan branch (keep an `empty` branch to `checkout` from if you frequently use this)

```bash
git checkout --orphan foobar
git rm --cached *  # I suggest VSCode's `Ustage All Changes`            
echo haha > readme.md && git add readme.md && git commint -m 'initial'
git push --set-upstream origin foobar
```



## Vim 

- insert output of a command

Press ':' in command mode would switch to command-line mode, then you can use `!command` to execute the command you want, such as `!ls`.

However, if you _don't_ press ':', but _directly_ press `!*command` ^[`*` means any normal key, for example, if you type `!als`, the command to execute will be `ls`] instead, the output of the command will be _inserted_ into the current document and _replace_ the current line.

- paste as is

```
set paste
```

- copy to clipboard (may need install `vim-gui-common`)

```
set clipboard=unnamedplus
```
