# blogdown






## usage



### homesite

```
[permalinks]
  post = "/:sections/:slug/"
```

refer to [here](https://gohugo.io/content-management/sections/) for `sections`, the most important thing is to create `_index.md` in the directory containing `.Rmd`



### cross-reference

The simplest way is `[text](/post/.../slug)`, if the url of result `.html` is fixed (see `[permalinks]` in `config.toml`),

Another option is to utilize _relative_ position of input files (absolute postion is forbidden since `ref` would cause error). From Hugo's view, the input file is `.html` produced by knitr. `.Rmd` is fixed. An important requirement is to create `_index.md` in the directory containing input files. The syntax is as follows ^[Due to the existence of `.` in filename, you have to wrap filename by `""`, such as `` `r htmltools::HTML('&#123;{% ref "foo.html" %}}')` ``. But the `--smart` option of Pandoc would ruin `""` (`\"` isn't useful since it would be convertd to `&quot;`). So you can only use R code to produce the `relref` shortcode.]:

```
[link text](``r ''`r blogdown::shortcode('relref', 'relative/path/to/filename.html')`)
```



### shortcode

Basically, shortcode is calling `{{% shortcodename parameters %}}`:

- with markdown: `{{% myshortcode %}}Hello **World!**{{% /myshortcode %}}`
- without markdown: `{{< myshortcode >}}<p>Hello <strong>World!</strong></p>{{< /myshortcode >}}`

In the first form, the text in between are treated as markdown. Ironically, it's rendered by Pandoc's rules in **blogdown**. So we'd better use the second form.

`htmltools::HTML()` in `.Rmd` can escape text from Pandoc and appear in `.html` verbatim. This provides us a way to write Hugo shortcode. I explored for a while and conclude the following ways:

1. ``` ``r ''`r htmltools::HTML('...')` ```
1. ``` ``r ''`r blogdown::shortcode(...) ```





### Tips

- after you rename a `.Rmd` file, remember to clean the old `.html` file (especially when you move `.Rmd`, otherwise there would be two post with same title and _slug_)








## theme



### 测试 theme

Hugo 的 theme 都会自带 exampleSite，如果你想自己 build （比如修改 exampleSite 之后看看效果）：

```
cd theme-name/exampleSite
hugo --themesDir ../../ -t theme-name
```



### tranquilpeak-theme

> 这个 theme 最吸引我的是 category 页面，但随着 nutshell 和 memoir 的独立，也该换个好看的 theme了。blogdown 最棒的是重心在 markdown，输出格式可以随便换。

[user doc](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/docs/user.md)

1. only files under `content/post/` directory is categoried ^[you may search `where .Data.Pages "Type" "post"`]
1. multiple categories will be treated as hierarchy.
1. tag and category must be vector (maybe a bug)

    error

    ```yaml
    tags: foobar
    ```

    right

    ```yaml
    tags: 
      - foobar
    ```

