# bookdown，将来写一本书时可能用到的



## content

### conventions 

- ``` `` ``` for inline code, file name and menu command
- **bold** to indicate special meaning ^[For example, in normal context, knitr is treated as a typo; but **knitr** means a R package]
-  _italic_ to emphasis important points 

###  custom header number and filename 

```markdown
## An Introduction {#my-custom-id-used-for-html-filename}
## unnumbered chapter {-}
## another unnumbered chapter {.unnumbered}
### section is also okay {#demo-section -}
```


## configuration 

### `_bookdown.yml`

```yaml
book_filename: *
output_dir: gitbook
delete_merged_file: yes
new_session: yes
language:
  label:
    fig: "Figure "
    tab: "Table "
  ui:
    edit: "Edit"
    chapter_name: "Chapter "
rmd_files:
  - "index.Rmd"
  - "body.Rmd"
```

### `_output.yml`

```yaml
bookdown::gitbook:
  dev: svglite
  split_by: section+number
  config:
    toc:
      collapse: section
      before: |
        <li><span>one line</span></li>
        <li><span>a second line</span></li>
      after: <li><a href="https://github.com/rstudio/bookdown" >Built by R bookdown</a></li>
    edit: https://github.com/dongzhuoer/*/edit/master/%s
    sharing:
      github: yes
      facebook: no
      twitter: no
```

### `index.Rmd`

```
---
title: "*"
author: "Zhuoer Dong"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
description: "*"
github-repo: dongzhuoer/*
---

## Perface {#perface -}
```


## others

- you may inset the following to the head of chapter `.Rmd`

  ```yaml
  knit: "bookdown::preview_chapter"
  ```

- you should use `-` rather than `_` for figure label, to make cross-reference work.


## build others' bookdown book in my preference


## customize other's book

关于目录

  - 章超过一页一般就collapse，如 r4ds, rmarkdown
  - 所有内容在 2～3页，展开显示，如 blogdown
  - 子标题严重不均匀，尤其要展开，如 bookdown

## Tips

### parse dependency

```bash
# possibly used pacakge
cat *.Rmd | grep -Po '[\w\.]+(?=::)' | sort -u | sed 's/$/,/' 
# cited package
cat *.Rmd | grep -Po '(?<=\[@R-)[\w\.]+' | sort -u | sed 's/$/,/' 
```

## build on travis

We offer two examples:

- r4ds: https://github.com/dongzhuoer/build-r4ds/blob/master/.travis.yml
- yihui-blogdown: https://github.com/dongzhuoer/build-yihui-blogdown/blob/master/.travis.yml

### details

The biggest restraint is that `bookdown::render_book()` requires workspace at the book folder.

For _blogdown_, `.Rmd` lives in `docs/`. If you `setwd()` to there, many paths would be relative to it (like `../../output`, `../../extra/_output.yaml`). 

So I thought about adding a environment variable `input_sub_dir`. But _blogdown_ doesn't collaborate, it refer to the some source code of the package by `../R/***.R`.

Suddenly, I realized that instead of setting every path relative to workspace, we can have `to_work_dir` to walk to `$work_dir`. In this way, every other path remains unchanged (`output`, `extra/_output.yaml`), user only need to customize `rmd_dir` & `to_work_dir`, like `rmd_dir=. to_work_dir=..`, `rmd_dir=docs to_work_dir=../..`.

## add a new book


1. clone Git repo (`github-copy user/repo`)
1. build book on local: 
   ```r
   bookdown::render_book(''); browseURL('_book/index.html')
   ```
1. create a repo on GitLab: 
   - open `empty`, 
   - `export repo=repo_name`
   - push to GitLab using following code
   ```bash
   git remote add gitlab git@gitlab.com:dongzhuoer/$repo.gitbook.git
   git push -u gitlab master
   git remote remove gitlab
   ```
1. create build repo
   - create repo on GitHub
   - copy a `build-*` and rename, remove old remote, then push to GitHub the normal way

1. travis CI
   add tokens to environment variable (maybe )


1. `bookdown.dongzhuoer.com`
