# Linux tools

- `which`
- `whatis` 
- `apropos`
- `type`






## Git



### clean 

The best way is to delete the folder and clone again.

```bash
git reset --hard	 # revert all modified files
git clean -fd		 # remove all untracked files and folders
git-rm-big path/to/file    # remove big files, my bash alias
git gc --aggressive --prune=all   # GC
```



### advanced

- untrack files

```bash
git rm --cached path/to/file
git update-index --assume-unchanged path/to/file
```

- orphan branch

```bash
git checkout --orphan foobar
git rm --cached *  # I suggest VSCode's `Ustage All Changes`            
echo haha > readme.md && git add readme.md && git commint -m 'initial'
git push --set-upstream origin foobar
```

Or if you frequently add new orphan branch, you can keep an `empty` branch to `checkout` from.



### config, alias

- config

```bash
git config --global user.name "Zhuoer Dong"
```

`~/.gitconfig`
```
[user]
	name = Zhuoer Dong
```

- print alias

```bash
$git help co
'co' is aliased to 'checkout'
```






## Vim 



### insert output of a command

Press ':' in command mode would switch to command-line mode, then you can use `!command` to execute the command you want, such as `!ls`.

However, if you _don't_ press ':', but _directly_ press `!*command` ^[`*` means any normal key, for example, if you type `!als`, the command to execute will be `ls`] instead, the output of the command will be _inserted_ into the current document and _replace_ the current line.



### copy and paste

- paste as is

```
set paste
```

- copy to clipboard ^[may need install `vim-gui-common`]

```
set clipboard=unnamedplus
```







## privoxy

`privoxy` can turn socks proxy into http proxy.



### example

`privoxy` is pretty useful when some program can't use socks proxy, but still need to bypass GFW.

`sudo vim /etc/privoxy/shadowsocks.config`
```
user-manual /usr/share/doc/privoxy/user-manual
logfile logfile
listen-address  127.0.0.1:1081
listen-address  [::1]:1081
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
forward-socks5 / 127.0.0.1:1080 .
```

`sudo vim /etc/systemd/system/privoxy-ss.service`
```
[Unit]
Description=Tranfrom socks5 proxy to http proxy using privoxy
Documentation=man:privoxy(8) 
Documentation=https://www.privoxy.org/user-manual/
After=network.target
Wants=haproxy-ss.service

[Service]
ExecStart=/usr/sbin/privoxy --no-daemon --pidfile /var/run/privoxy-ss.pid --user privoxy /etc/privoxy/shadowsocks.config 
ExecStopPost=/bin/rm -f /var/run/privoxy-ss.pid

[Install]
WantedBy=multi-user.target
```




### other usage


- `listen-address` can be retricted to the computer's real IP ^[I have used this feature to temporarily let other people inside NKU LAN break GFW.].
- `forward-socks5 .github.com 127.0.0.1:1080 .` can use shadowsocks only for certain domain and direct connect for others.
    





  
    



