# (PART) Linux {-}

主要在Linux运行，与Linux密切相关的工具

# Linux system management

- [understanding `~/.bashrc`](https://dongzhuoer.com/post/caprice/2018/bashrc/)






## inspect, monitor, maintain



### inspect system

- system version

```bash
uname -r                       # kernel version
lsb_release -cs                # Ubuntu version
cat /etc/debian_version        # Debian version
```

- cpu

```bash
grep 'physical id' /proc/cpuinfo | sort -u          # processors
grep 'core id'     /proc/cpuinfo | sort -u | wc -l  # cores per processors
grep 'processor'   /proc/cpuinfo | sort -u | wc -l  # threads
```



### monitor system

- file system

```bash
du . -d 1 -h
df -h
sudo blkid
lsblk # -f
```



### maintain system

- when you always see a system alert, `sudo rm /var/crash/*`






## account



### add account 

```bash
sudo useradd -m -s /bin/bash username  
echo 'username:password' | sudo chpasswd
```

Don't use `-p password`, it's wrong and **unsafe**. Because it saves the password directly instead of hashed code into `/etc/shadow` ^[You can use `sudo grep username /etc/shadow` to verify, note that `password` is shown unencrypted.].



### group

```bash
sudo usermod -g group username                       # change initial group
sudo usermod [-a] -G group1, group2 username # append or change
```

Add user to `sudo` group (`wheel` for CentOS) can assign root privilege.



### others

- In `man` page, `LOGIN` (`-l` option) means username 
- `id`
- In `/etc/passwd`, the 3rd field indicates the number of days (since 1970-01-01) since last password change, empty indicates never and `0` forces user to change.






## SSH & compress



### SSH

- set up SSH

```bash
ssh-keygen; 
ssh-copy-id user@ip; 
ssh-add  
```

If you find something wrong, ensure that the user's login shell is `/bin/bash`.

- when you reinstall VPS without changing IP

```bash
ssh-keygen -R ip-or-hostname 
```



### compress

- `unar`

可自动解决 `.zip` 乱码问题

```
unar
lsar
```

- `gzip`

```bash
gzip filename           # make `filename.gz`, delete `filename`
gip -k filename         # keep original file
gzip -f filename.gz     #  `-f` force compressing file ended with `.gz`
gzip -t filename.gz     # check integrity
gzip filename -c > filename.gz
```






## package management



### Ubuntu list files

```bash
apt-file list -F pakage # an online package,    `-F` means `--fixed-string`
dpkg -c package-file    # a .deb file,          use `dpkg-deb -c`
dpkg -L package         # an installed package, use `dpkg-query -L`
```



### CentOS EPEL

1. the simplest way is `yum -y install epel-release`

1. you can also create `/etc/yum.repos.d/epel.repo` ^[when you meet xz compression error, `sudo rm -rf /var/cache/yum/x86_64/6/epel/`]:

   ```
   [epel]
   name = epel packages
   baseurl = https://mirrors.tuna.tsinghua.edu.cn/epel/7/x86_64/
   gpgcheck = 0
   enabled = 1
   ```






## systemd & process control



### systemd

- [阮一峰中文教程](http://www.ruanyifeng.com/blog/2016/03/systemd-tutorial-commands.html)
- [Red Hat documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/chap-Managing_Services_with_systemd.html)
- `man systemd.service`
- [override some settings in `.service` without modifying original file](https://dongzhuoer.com/post/caprice/2018/systemd-crash-teach-me-overwriting-service)



### list process

据鸟哥说，`ps` 的选项过于复杂，与其逐一理解，不如背一些常用组合。 

```bash
ps aux  # 观察系统所有的程序数据
ps -lA  # 同上

ps axjf #连同部分程序树状态
pstree
```



### kill process

```bash
kill -signal %job-number   
```

`man 7 signal` for details, following are most important ones:

| signal | action                                      |
|:------:|:---------------------------------------------|
|    1   | reload the configuration file of parameters |
|    2   | the same as `C-c`                           |
|    9   | force stopping                              |
|   15   | normally exit                               |





